wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.41.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    python_version: 3.9.13
    start_time: 1717003325
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 7
      - 13
      4: 3.9.13
      5: 0.12.16
      6: 4.41.1
      8:
      - 1
      - 5
      9:
        1: transformers_trainer
accelerator_config:
  desc: null
  value:
    dispatch_batches: null
    even_batches: true
    gradient_accumulation_kwargs: null
    non_blocking: false
    split_batches: false
    use_seedable_sampler: true
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
auto_find_batch_size:
  desc: null
  value: false
batch_eval_metrics:
  desc: null
  value: false
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
data_seed:
  desc: null
  value: null
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_persistent_workers:
  desc: null
  value: false
dataloader_pin_memory:
  desc: null
  value: true
dataloader_prefetch_factor:
  desc: null
  value: null
ddp_backend:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
debug:
  desc: null
  value: []
deepspeed:
  desc: null
  value: null
disable_tqdm:
  desc: null
  value: false
dispatch_batches:
  desc: null
  value: null
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
do_train:
  desc: null
  value: false
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
eval_do_concat_batches:
  desc: null
  value: true
eval_steps:
  desc: null
  value: null
eval_strategy:
  desc: null
  value: 'no'
evaluation_strategy:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: []
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
    xla_fsdp_v2: false
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
full_determinism:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hub_always_push:
  desc: null
  value: false
hub_model_id:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
ignore_data_skip:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
include_tokens_per_second:
  desc: null
  value: false
jit_mode_eval:
  desc: null
  value: false
label_names:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
learning_rate:
  desc: null
  value: 5.0e-05
length_column_name:
  desc: null
  value: length
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ./logs
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 500
logging_strategy:
  desc: null
  value: steps
lr_scheduler_kwargs:
  desc: null
  value: {}
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: null
mp_parameters:
  desc: null
  value: ''
neftune_noise_alpha:
  desc: null
  value: null
no_cuda:
  desc: null
  value: false
num_train_epochs:
  desc: null
  value: 3
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
optim_target_modules:
  desc: null
  value: null
output_dir:
  desc: null
  value: ./results
overwrite_output_dir:
  desc: null
  value: false
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 64
per_device_train_batch_size:
  desc: null
  value: 16
per_gpu_eval_batch_size:
  desc: null
  value: null
per_gpu_train_batch_size:
  desc: null
  value: null
prediction_loss_only:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
ray_scope:
  desc: null
  value: last
remove_unused_columns:
  desc: null
  value: true
report_to:
  desc: null
  value:
  - mlflow
  - tensorboard
  - wandb
restore_callback_states_from_checkpoint:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
run_name:
  desc: null
  value: ./results
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
save_safetensors:
  desc: null
  value: true
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: null
seed:
  desc: null
  value: 42
skip_memory_metrics:
  desc: null
  value: true
split_batches:
  desc: null
  value: null
tf32:
  desc: null
  value: null
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
torchdynamo:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
use_cpu:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 500
weight_decay:
  desc: null
  value: 0.01
